vendor:
  fetch:
    url: https://dummyjson.com/products
    apikey: sdfjkJ
  sync:
    url: http://spnav.sellparker.local:7047/SP_NAV2013R2Test/WS/Sell%20%26%20Parker/Page/WSVendor

invoice:
  fetch:
    url: https://jsonplaceholder.typicode.com/posts
    apikey: sdfjkJ
  sync:
    url: https://jsonplaceholder.typicode.com/posts

auth:
  ntlm:
    username: rojan.shrestha
    password: murkyGlu354